### ISSUE TITLE
Dokončit instantní vyhledávání (checkbox)

### ISSUE THREAD

**Issue by otoupal93** [PB138SearchingOpenDocument/OdsSearch#2]

**Comment by arrynn** [comment]
Co je instantne vyhladavanie ?

**Comment by otoupal93** [comment]
Že to bude po zadání a odebrání každého písmenka zobrazovat výsledky aniž bys musel mačkat tlačítko. něco jako google když ti nabízí výsledky. :-) , ale myslím že když by jsme to tam dali tak by to mělo být volitelné.
